sudo: false

language: node_js
node_js:
  - 6
  - 8

before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

script:
  - npm run coverage -- --no-cache --runInBand

after_success:
  - npm run coverage:report
